dbtlearning:
  outputs:
    dev:
      account: YLKOKBT-TA35348
      database: dev
      password: Cloudjsks@2025
      role: ACCOUNTADMIN
      schema: bronze_airbnb
      threads: 4
      type: snowflake
      user: JAGANNATH
      warehouse: COMPUTE_WH
  target: dev
