sources:
  - name: src_schema
    schema: bronze_airbnb

    tables:
        - name: hosts
          identifier: src_hosts

        - name: listings
          identifier: src_listings

        - name: reviews
          identifier: src_reviews